#ifndef _GLOBALS_H_
#define _GLOBALS_H_

#include <Arduino.h>

#define DEBUG
#ifdef DEBUG
	#define DEBUG_BAUDRATE		(115200)
	#define DEBUG_PRINT(...)	Serial.print(__VA_ARGS__)
	#define DEBUG_PRINTLN(...)	Serial.println(__VA_ARGS__)
#else
	#define DEBUG_PRINT(...)
	#define DEBUG_PRINTLN(...)
#endif

#define PLAYER_BUSY_PIN			(3)
#define PLAYER_RX_PIN			(4)
#define PLAYER_TX_PIN			(5)
#define GPS_RX_PIN				(6)
#define GPS_TX_PIN				(7)
#define US_TRIG_PIN				(8)
#define US_ECHO_PIN				(9)
#define LED_PIN					(10)
#define FAN_PIN					(11)
#define BUTTON_UP_PIN			(A0)
#define BUTTON_DOWN_PIN			(A1)
#define BUTTON_ENTER_PIN		(A2)
#define BUTTON_MODE_PIN			(A3)
#define SDA_PIN					(A4)
#define SCL_PIN					(A5)

#define BUTTON_UP_MASK			(0x01)
#define BUTTON_DOWN_MASK		(0x02)
#define BUTTON_ENTER_MASK		(0x04)
#define BUTTON_MODE_MASK		(0x08)
#define BUTTON_UP_DOWN_MASK		(BUTTON_UP_MASK | BUTTON_DOWN_MASK)

#define HAT_MODE_MUSIC			(0)
#define HAT_MODE_DISTANCE		(1)
#define HAT_MODE_LIGHT			(2)
#define HAT_MODE_FAN			(3)
#define HAT_MODE_INFORMATION	(4)
#define HAT_MODES_COUNT			(5)

#define US_MAX_DISTANCE			(200)
#define GPS_BAUDRATE			(9600)
#define HAT_VOICES_MAX_NUMBER	(100)
#define TALKING_LIST_SIZE		(30)

#define pgm_read_ptr(addr)		(void *)__LPM_word((uint16_t)(addr))
#define PARRAY(name, ...)		const name[] PROGMEM = {__VA_ARGS__}
#define PCHARS(name, ...)		char PARRAY(name, __VA_ARGS__)

enum {
	HAT_VOICE_SONGS = 1,
	HAT_VOICE_DISTANCE,
	HAT_VOICE_LIGHT,
	HAT_VOICE_FAN,
	HAT_VOICE_INFORMATION,
	HAT_VOICE_FIX_ORDER,
	HAT_VOICE_RANDOM_ORDER,
	HAT_VOICE_FOLDER_NUMBER,
	HAT_VOICE_EQ_NORMAL,
	HAT_VOICE_EQ_ROCK,
	HAT_VOICE_EQ_POP,
	HAT_VOICE_EQ_JAZZ,
	HAT_VOICE_EQ_CLASSICAL,
	HAT_VOICE_STOP,
	HAT_VOICE_WARNING,
	HAT_VOICE_CLOSE,
	HAT_VOICE_DISTANCE_SENSOR,
	HAT_VOICE_CENTIMETERS,
	HAT_VOICE_LIGHT_SENSOR,
	HAT_VOICE_LUX,
	HAT_VOICE_TEMPERATURE_SENSOR,
	HAT_VOICE_DEGREES_CELSIUS,
	HAT_VOICE_FAN_ON,
	HAT_VOICE_FAN_OFF,
	HAT_VOICE_LED_ON,
	HAT_VOICE_LED_OFF,
	HAT_VOICE_THE_TIME_IS,
	HAT_VOICE_AND_MINUTE,
	HAT_VOICE_AND_QUARTER,
	HAT_VOICE_AND_HALF,
	HAT_VOICE_MINUTES,
	HAT_VOICE_MORNING,
	HAT_VOICE_AFTERNOON,
	HAT_VOICE_EVENING,
	HAT_VOICE_NIGHT,
	HAT_VOICE_TODAY,
	HAT_VOICE_SUNDAY,
	HAT_VOICE_MONDAY,
	HAT_VOICE_TUESDAY,
	HAT_VOICE_WEDNESDAY,
	HAT_VOICE_THURSDAY,
	HAT_VOICE_FRIDAY,
	HAT_VOICE_SATURDAY,
	HAT_VOICE_JANUARY,
	HAT_VOICE_FEBRUARY,
	HAT_VOICE_MARCH,
	HAT_VOICE_APRIL,
	HAT_VOICE_MAY,
	HAT_VOICE_JUNE,
	HAT_VOICE_JULY,
	HAT_VOICE_AUGUST,
	HAT_VOICE_SEPTEMBER,
	HAT_VOICE_OCTOBER,
	HAT_VOICE_NOVEMBER,
	HAT_VOICE_DECEMBER,
	HAT_VOICE_THOUSANDS,
	HAT_VOICE_AND,
	HAT_VOICE_PRESSURE_SENSOR,
	HAT_VOICE_PSI,
	HAT_VOICE_NO_SATELLITE,
	HAT_VOICE_SATELLITES,
	HAT_VOICE_SPEED,
	HAT_VOICE_KPH,
	HAT_VOICE_ALTITUDE,
	HAT_VOICE_METERS,
	HAT_VOICE_DIRECTION,
	HAT_VOICE_DEGREES,
	HAT_VOICE_NORTH,
	HAT_VOICE_SOUTH,
	HAT_VOICE_EAST,
	HAT_VOICE_WEST,
	HAT_VOICES_COUNT,
	HAT_VOICES_NUMBER_ZERO = 100,
};

#endif
